import type { InventoryItem, Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "lemon-butter-pasta",
    name: "Lemon butter pasta",
    kind: "food",
    required: ["pasta", "butter", "lemon", "parmesan"],
    optional: ["garlic"],
    minutes: 20,
    skill: "easy",
    notes: "Weeknight default. Uses the lemon before it fades.",
  },
  {
    id: "aglio-olio",
    name: "Aglio e olio",
    kind: "food",
    required: ["pasta", "garlic", "olive oil"],
    optional: ["parmesan"],
    minutes: 18,
    skill: "easy",
    notes: "Pantry-true. Hierarchy does not invent missing oil.",
  },
  {
    id: "tomato-spaghetti",
    name: "Tomato garlic spaghetti",
    kind: "food",
    required: ["pasta", "tomato", "garlic", "olive oil"],
    optional: ["parmesan", "basil"],
    minutes: 30,
    skill: "easy",
    notes: "High co-occurrence trio: tomato, garlic, oil.",
  },
  {
    id: "chicken-bowl",
    name: "Roast chicken grain bowl",
    kind: "food",
    required: ["chicken", "rice", "kale", "lemon"],
    optional: ["olive oil"],
    minutes: 25,
    skill: "easy",
    notes: "Prioritizes leftover chicken and near-expiry greens.",
  },
  {
    id: "chicken-dijon",
    name: "Chicken Dijon skillet",
    kind: "food",
    required: ["chicken", "dijon", "onion"],
    optional: ["milk", "butter"],
    minutes: 28,
    skill: "medium",
    notes: "Uses roast chicken without asking for a new protein.",
  },
  {
    id: "kale-parmesan",
    name: "Lemon kale with parmesan",
    kind: "food",
    required: ["kale", "lemon", "parmesan"],
    optional: ["olive oil", "garlic"],
    minutes: 12,
    skill: "easy",
    notes: "The expiry-first salad. Fat and acid fix the brassica.",
  },
  {
    id: "omelette",
    name: "French omelette",
    kind: "food",
    required: ["eggs", "butter"],
    optional: ["parmesan"],
    minutes: 8,
    skill: "medium",
    notes: "Two-ingredient truth. Skill is the only hard part.",
  },
  {
    id: "potato-hash",
    name: "Potato hash with eggs",
    kind: "food",
    required: ["potato", "onion", "eggs"],
    optional: ["butter"],
    minutes: 30,
    skill: "easy",
    notes: "Fridge-and-pantry dinner that still feels cooked.",
  },
  {
    id: "honey-carrots",
    name: "Honey garlic carrots",
    kind: "food",
    required: ["carrot", "honey", "garlic", "butter"],
    optional: [],
    minutes: 22,
    skill: "easy",
    notes: "Sweet-savory side that can stand as a small plate.",
  },
  {
    id: "beans-rice",
    name: "Black beans and rice",
    kind: "food",
    required: ["black beans", "rice", "onion"],
    optional: ["lime", "garlic"],
    minutes: 25,
    skill: "easy",
    notes: "Pantry complete. Lime is a preference, not a blocker.",
  },
  {
    id: "old-fashioned",
    name: "Old Fashioned",
    kind: "cocktail",
    required: ["bourbon", "angostura", "sugar"],
    optional: ["orange"],
    minutes: 4,
    skill: "easy",
    notes: "Whiskey hierarchy covers bourbon. Sugar or simple syrup both qualify.",
  },
  {
    id: "manhattan",
    name: "Manhattan",
    kind: "cocktail",
    required: ["bourbon", "sweet vermouth", "angostura"],
    optional: [],
    minutes: 4,
    skill: "easy",
    notes: "Classic three-bottle build. High molecular + co-occurrence score.",
  },
  {
    id: "negroni",
    name: "Negroni",
    kind: "cocktail",
    required: ["gin", "campari", "sweet vermouth"],
    optional: ["orange"],
    minutes: 3,
    skill: "easy",
    notes: "Equal parts. The shelf already knows this drink.",
  },
  {
    id: "boulevardier",
    name: "Boulevardier",
    kind: "cocktail",
    required: ["bourbon", "campari", "sweet vermouth"],
    optional: ["orange"],
    minutes: 3,
    skill: "easy",
    notes: "Negroni's whiskey cousin. Same vermouth, different base.",
  },
  {
    id: "martini",
    name: "Martini",
    kind: "cocktail",
    required: ["gin", "dry vermouth"],
    optional: ["lemon"],
    minutes: 3,
    skill: "easy",
    notes: "Dry vermouth is not interchangeable with sweet without a note.",
  },
  {
    id: "gin-tonic",
    name: "Gin and tonic",
    kind: "cocktail",
    required: ["gin", "tonic"],
    optional: ["lime", "lemon"],
    minutes: 2,
    skill: "easy",
    notes: "Highball that should always rank when both bottles are open.",
  },
  {
    id: "whiskey-sour",
    name: "Whiskey sour",
    kind: "cocktail",
    required: ["bourbon", "lemon", "simple syrup"],
    optional: ["egg"],
    minutes: 5,
    skill: "medium",
    notes: "Citrus + whiskey. Egg white is optional, never required.",
  },
  {
    id: "americano",
    name: "Americano",
    kind: "cocktail",
    required: ["campari", "sweet vermouth"],
    optional: ["orange"],
    minutes: 3,
    skill: "easy",
    notes: "Two bottles plus soda. Lowest-friction bitter drink.",
  },
  {
    id: "daiquiri",
    name: "Daiquiri",
    kind: "cocktail",
    required: ["rum", "lime", "simple syrup"],
    optional: [],
    minutes: 5,
    skill: "medium",
    notes: "Usually an Almost — rum is the typical Smart Buy.",
  },
  {
    id: "sidecar",
    name: "Sidecar",
    kind: "cocktail",
    required: ["cognac", "cointreau", "lemon"],
    optional: [],
    minutes: 5,
    skill: "medium",
    notes: "Cognac is the missing bottle in the demo bar.",
  },
];

export function sampleInventory(now = new Date()): InventoryItem[] {
  const iso = now.toISOString();
  const day = (offset: number) => {
    const d = new Date(now);
    d.setDate(d.getDate() + offset);
    return d.toISOString().slice(0, 10);
  };
  const item = (
    partial: Omit<InventoryItem, "id" | "lastUpdated" | "tags" | "userNotes" | "source" | "confidence"> &
      Partial<Pick<InventoryItem, "source" | "confidence" | "tags">>,
  ): InventoryItem => ({
    id: crypto.randomUUID(),
    lastUpdated: iso,
    tags: partial.tags ?? [],
    userNotes: "",
    source: partial.source ?? "demo",
    confidence: partial.confidence ?? 1,
    ...partial,
  });

  return [
    item({ displayName: "Maker's Mark", normalizedName: "bourbon", category: "spirit", quantity: { value: 0.7, unit: "bottle" }, expiry: null, location: "bar_shelf" }),
    item({ displayName: "Tanqueray", normalizedName: "gin", category: "spirit", quantity: { value: 0.6, unit: "bottle" }, expiry: null, location: "bar_shelf" }),
    item({ displayName: "Campari", normalizedName: "campari", category: "spirit", quantity: { value: 0.5, unit: "bottle" }, expiry: null, location: "bar_shelf" }),
    item({ displayName: "Carpano Antica", normalizedName: "sweet vermouth", category: "mixer", quantity: { value: 0.4, unit: "bottle" }, expiry: day(40), location: "fridge" }),
    item({ displayName: "Dolin Dry", normalizedName: "dry vermouth", category: "mixer", quantity: { value: 0.35, unit: "bottle" }, expiry: day(25), location: "fridge" }),
    item({ displayName: "Angostura", normalizedName: "angostura", category: "mixer", quantity: { value: 0.8, unit: "bottle" }, expiry: null, location: "bar_shelf" }),
    item({ displayName: "Cointreau", normalizedName: "cointreau", category: "spirit", quantity: { value: 0.55, unit: "bottle" }, expiry: null, location: "bar_shelf" }),
    item({ displayName: "Fever-Tree tonic", normalizedName: "tonic", category: "mixer", quantity: { value: 4, unit: "count" }, expiry: day(90), location: "pantry" }),
    item({ displayName: "Simple syrup", normalizedName: "simple syrup", category: "mixer", quantity: { value: 200, unit: "ml" }, expiry: day(14), location: "fridge" }),
    item({ displayName: "Sugar", normalizedName: "sugar", category: "pantry", quantity: { value: 400, unit: "g" }, expiry: null, location: "pantry" }),
    item({ displayName: "Limes", normalizedName: "lime", category: "produce", quantity: { value: 3, unit: "count" }, expiry: day(5), location: "fridge" }),
    item({ displayName: "Lemons", normalizedName: "lemon", category: "produce", quantity: { value: 2, unit: "count" }, expiry: day(4), location: "fridge" }),
    item({ displayName: "Eggs", normalizedName: "eggs", category: "protein", quantity: { value: 6, unit: "count" }, expiry: day(8), location: "fridge" }),
    item({ displayName: "Butter", normalizedName: "butter", category: "dairy", quantity: { value: 1, unit: "count" }, expiry: day(18), location: "fridge" }),
    item({ displayName: "Whole milk", normalizedName: "milk", category: "dairy", quantity: { value: 500, unit: "ml" }, expiry: day(3), location: "fridge", tags: ["priority_use"] }),
    item({ displayName: "Parmesan", normalizedName: "parmesan", category: "dairy", quantity: { value: 120, unit: "g" }, expiry: day(12), location: "fridge" }),
    item({ displayName: "Dijon", normalizedName: "dijon", category: "condiment", quantity: { value: 1, unit: "count" }, expiry: day(80), location: "fridge" }),
    item({ displayName: "Leftover roast chicken", normalizedName: "chicken", category: "protein", quantity: { value: 350, unit: "g" }, expiry: day(1), location: "fridge", tags: ["priority_use"] }),
    item({ displayName: "Kale", normalizedName: "kale", category: "produce", quantity: { value: 1, unit: "bunch" }, expiry: day(2), location: "fridge", tags: ["priority_use"] }),
    item({ displayName: "Carrots", normalizedName: "carrot", category: "produce", quantity: { value: 5, unit: "count" }, expiry: day(9), location: "fridge" }),
    item({ displayName: "Yellow onion", normalizedName: "onion", category: "produce", quantity: { value: 2, unit: "count" }, expiry: day(14), location: "pantry" }),
    item({ displayName: "Garlic", normalizedName: "garlic", category: "produce", quantity: { value: 1, unit: "count" }, expiry: day(16), location: "pantry" }),
    item({ displayName: "Yukon potatoes", normalizedName: "potato", category: "produce", quantity: { value: 4, unit: "count" }, expiry: day(20), location: "pantry" }),
    item({ displayName: "Spaghetti", normalizedName: "pasta", category: "pantry", quantity: { value: 400, unit: "g" }, expiry: null, location: "pantry" }),
    item({ displayName: "Olive oil", normalizedName: "olive oil", category: "pantry", quantity: { value: 0.6, unit: "bottle" }, expiry: null, location: "pantry" }),
    item({ displayName: "Crushed tomatoes", normalizedName: "tomato", category: "pantry", quantity: { value: 1, unit: "count" }, expiry: day(200), location: "pantry" }),
    item({ displayName: "Jasmine rice", normalizedName: "rice", category: "pantry", quantity: { value: 600, unit: "g" }, expiry: null, location: "pantry" }),
    item({ displayName: "Black beans", normalizedName: "black beans", category: "pantry", quantity: { value: 2, unit: "count" }, expiry: day(300), location: "pantry" }),
    item({ displayName: "Honey", normalizedName: "honey", category: "pantry", quantity: { value: 1, unit: "count" }, expiry: null, location: "pantry" }),
  ];
}
