import type { Recipe, RecipeKind, Skill } from "./types";

function r(
  id: string,
  name: string,
  kind: RecipeKind,
  required: string[],
  optional: string[],
  minutes: number,
  skill: Skill,
  notes: string,
): Recipe {
  return { id, name, kind, required, optional, minutes, skill, notes };
}

/** Cocktail half of the curated corpus (SEED_VERSION 6). */
export const COCKTAIL_RECIPES: Recipe[] = [
  r("old-fashioned", "Old Fashioned", "cocktail", ["bourbon", "sugar", "angostura"], ["orange"], 4, "easy", "The whiskey already open."),
  r("manhattan", "Manhattan", "cocktail", ["bourbon", "sweet vermouth", "angostura"], [], 3, "easy", "Vermouth is open."),
  r("rye-manhattan", "Rye Manhattan", "cocktail", ["rye", "sweet vermouth", "angostura"], [], 3, "easy", "Rye sibling on the same bones."),
  r("negroni", "Negroni", "cocktail", ["gin", "campari", "sweet vermouth"], ["orange"], 3, "easy", "Equal parts."),
  r("boulevardier", "Boulevardier", "cocktail", ["bourbon", "campari", "sweet vermouth"], ["orange"], 3, "easy", "Whiskey Negroni."),
  r("martini", "Martini", "cocktail", ["gin", "dry vermouth"], ["lemon"], 3, "easy", "Dry."),
  r("vodka-martini", "Vodka martini", "cocktail", ["vodka", "dry vermouth"], ["lemon"], 3, "easy", "Vodka path."),
  r("gin-tonic", "Gin and tonic", "cocktail", ["gin", "tonic"], ["lime"], 2, "easy", "Highball math."),
  r("vodka-tonic", "Vodka tonic", "cocktail", ["vodka", "tonic"], ["lime"], 2, "easy", "Clean highball."),
  r("whiskey-sour", "Whiskey sour", "cocktail", ["bourbon", "lemon", "simple syrup"], ["angostura"], 4, "easy", "The sour template."),
  r("americano", "Americano", "cocktail", ["campari", "sweet vermouth", "soda"], ["orange"], 2, "easy", "Low-ABV bitter."),
  r("gimlet", "Gimlet", "cocktail", ["gin", "lime", "simple syrup"], [], 3, "easy", "Three ingredients."),
  r("tom-collins", "Tom Collins", "cocktail", ["gin", "lemon", "simple syrup", "soda"], [], 4, "easy", "Tall and bright."),
  r("margarita", "Margarita", "cocktail", ["tequila", "cointreau", "lime"], [], 4, "easy", "Three ingredients."),
  r("ranch-water", "Ranch water", "cocktail", ["tequila", "soda", "lime"], [], 2, "easy", "Texas highball."),
  r("garibaldi", "Garibaldi", "cocktail", ["campari", "orange"], [], 2, "easy", "Bitter orange."),
  r("paper-plane", "Paper Plane", "cocktail", ["bourbon", "amaro", "aperol", "lemon"], [], 4, "medium", "Equal parts modern classic."),
  r("gold-rush", "Gold Rush", "cocktail", ["bourbon", "lemon", "honey"], [], 4, "easy", "Honey sour."),
  r("bees-knees", "Bee's Knees", "cocktail", ["gin", "lemon", "honey"], [], 4, "easy", "Prohibition honey."),
  r("whiskey-highball", "Whiskey highball", "cocktail", ["bourbon", "soda"], ["lemon"], 2, "easy", "Whiskey and bubbles."),
  r("campari-soda", "Campari soda", "cocktail", ["campari", "soda"], ["orange"], 1, "easy", "Simplest bitter."),
  r("tequila-old-fashioned", "Tequila Old Fashioned", "cocktail", ["tequila", "sugar", "angostura"], ["orange"], 4, "easy", "Agave on whiskey bones."),
  r("moscow-mule", "Moscow mule", "cocktail", ["vodka", "ginger beer", "lime"], [], 2, "easy", "Copper classic."),
  r("paloma", "Paloma", "cocktail", ["tequila", "grapefruit", "soda", "lime"], [], 3, "easy", "Citrus family may cover grapefruit."),
  r("whiskey-coffee", "Whiskey coffee", "cocktail", ["bourbon", "coffee"], ["sugar"], 3, "easy", "Morning path."),
  r("gin-rickey", "Gin rickey", "cocktail", ["gin", "lime", "soda"], [], 2, "easy", "No sugar."),
  r("orange-old-fashioned", "Orange Old Fashioned", "cocktail", ["bourbon", "orange bitters", "sugar"], ["orange"], 4, "easy", "Orange bitters variant."),
  r("aperol-tonic", "Aperol tonic", "cocktail", ["aperol", "tonic"], ["orange"], 2, "easy", "Light bitter highball."),
  r("vodka-soda", "Vodka soda", "cocktail", ["vodka", "soda"], ["lime"], 1, "easy", "Cleanest highball."),
  r("dirty-martini", "Dirty martini", "cocktail", ["gin", "dry vermouth", "olives"], [], 3, "easy", "Briny."),
  r("rye-old-fashioned", "Rye Old Fashioned", "cocktail", ["rye", "sugar", "angostura"], ["orange"], 4, "easy", "Rye path."),
  r("rye-sour", "Rye sour", "cocktail", ["rye", "lemon", "simple syrup"], ["angostura"], 4, "easy", "Rye sour."),
  r("martinez", "Martinez", "cocktail", ["gin", "sweet vermouth", "maraschino", "angostura"], [], 4, "medium", "Martini ancestor."),
  r("aperol-sour", "Aperol sour", "cocktail", ["aperol", "lemon", "simple syrup"], [], 4, "easy", "Bitter sour."),
  r("tequila-sour", "Tequila sour", "cocktail", ["tequila", "lemon", "simple syrup"], [], 4, "easy", "Agave sour."),
  r("maple-old-fashioned", "Maple Old Fashioned", "cocktail", ["bourbon", "maple", "angostura"], ["orange"], 4, "easy", "Sweetener family."),
  r("amaro-highball", "Amaro highball", "cocktail", ["amaro", "soda"], ["orange"], 2, "easy", "After-dinner tall."),
  r("vodka-gimlet", "Vodka gimlet", "cocktail", ["vodka", "lime", "simple syrup"], [], 3, "easy", "Vodka path."),
  r("daiquiri", "Daiquiri", "cocktail", ["rum", "lime", "simple syrup"], [], 4, "easy", "Rum is the Smart Buy."),
  r("dark-n-stormy", "Dark and Stormy", "cocktail", ["rum", "ginger beer", "lime"], [], 2, "easy", "Second rum unlock."),
  r("cuba-libre", "Cuba Libre", "cocktail", ["rum", "cola", "lime"], [], 2, "easy", "Third rum unlock."),
  r("rum-old-fashioned", "Rum Old Fashioned", "cocktail", ["rum", "sugar", "angostura"], ["orange"], 4, "easy", "Fourth rum unlock."),
  r("grog", "Grog", "cocktail", ["rum", "lime", "sugar", "water"], [], 3, "easy", "Fifth rum unlock."),
  r("honey-rum-sour", "Honey rum sour", "cocktail", ["rum", "honey", "lemon"], [], 4, "easy", "Sixth rum unlock."),
  r("jungle-bird", "Jungle Bird", "cocktail", ["rum", "campari", "pineapple", "lime", "simple syrup"], [], 5, "medium", "Seventh rum unlock."),
  r("hot-buttered-rum", "Hot buttered rum", "cocktail", ["rum", "butter", "sugar", "cinnamon"], [], 6, "easy", "Eighth rum unlock."),
  r("painkiller", "Painkiller", "cocktail", ["rum", "pineapple", "orange", "coconut milk"], [], 4, "easy", "Ninth rum unlock."),
  r("pina-colada", "Piña colada", "cocktail", ["rum", "pineapple", "coconut milk"], [], 4, "easy", "Tenth rum unlock."),
  r("sidecar", "Sidecar", "cocktail", ["cognac", "cointreau", "lemon"], [], 4, "easy", "Cognac is the miss."),
  r("brandy-alexander", "Brandy Alexander", "cocktail", ["cognac", "creme de cacao", "cream"], [], 4, "easy", "Second cognac unlock."),
  r("brandy-sour", "Brandy sour", "cocktail", ["cognac", "lemon", "simple syrup"], [], 4, "easy", "Third cognac unlock."),
  r("brandy-old-fashioned", "Brandy Old Fashioned", "cocktail", ["cognac", "sugar", "angostura"], ["orange"], 4, "easy", "Fourth cognac unlock."),
  r("aperol-spritz", "Aperol Spritz", "cocktail", ["aperol", "prosecco", "soda"], ["orange"], 2, "easy", "Prosecco already in."),
  r("french-75", "French 75", "cocktail", ["gin", "lemon", "simple syrup", "prosecco"], [], 5, "medium", "Sparkling family."),
  r("negroni-sbagliato", "Negroni Sbagliato", "cocktail", ["campari", "sweet vermouth", "prosecco"], ["orange"], 2, "easy", "Mistaken Negroni."),
  r("mimosa", "Mimosa", "cocktail", ["prosecco", "orange"], [], 2, "easy", "Brunch path."),
  r("champagne-cocktail", "Champagne cocktail", "cocktail", ["prosecco", "sugar", "angostura"], [], 3, "easy", "Bitters and bubbles."),
  r("mint-julep", "Mint julep", "cocktail", ["bourbon", "mint", "sugar"], [], 6, "medium", "Mint is in the fridge."),
  r("southside", "Southside", "cocktail", ["gin", "mint", "lime", "simple syrup"], [], 5, "medium", "Second mint unlock."),
  r("whiskey-smash", "Whiskey smash", "cocktail", ["bourbon", "mint", "lemon", "sugar"], [], 6, "medium", "Third mint unlock."),
  r("last-word", "Last Word", "cocktail", ["gin", "chartreuse", "maraschino", "lime"], [], 4, "medium", "Chartreuse Smart Buy."),
  r("bijou", "Bijou", "cocktail", ["gin", "chartreuse", "sweet vermouth"], [], 4, "medium", "Second Chartreuse unlock."),
  r("cloister", "Cloister", "cocktail", ["gin", "chartreuse", "grapefruit", "lemon"], [], 5, "medium", "Third Chartreuse unlock."),
  r("espresso-martini", "Espresso martini", "cocktail", ["vodka", "coffee liqueur", "coffee"], [], 6, "medium", "Coffee liqueur is the miss."),
  r("white-russian", "White Russian", "cocktail", ["vodka", "coffee liqueur", "cream"], [], 3, "easy", "Second coffee-liqueur unlock."),
  r("black-russian", "Black Russian", "cocktail", ["vodka", "coffee liqueur"], [], 2, "easy", "Third coffee-liqueur unlock."),
  r("bourbon-coffee-liqueur", "Bourbon coffee", "cocktail", ["bourbon", "coffee liqueur", "angostura"], [], 4, "easy", "Fourth coffee-liqueur unlock."),
  r("cosmopolitan", "Cosmopolitan", "cocktail", ["vodka", "cointreau", "lime", "cranberry"], [], 4, "easy", "Cranberry is the miss."),
  r("cape-codder", "Cape Codder", "cocktail", ["vodka", "cranberry", "lime"], [], 2, "easy", "Second cranberry unlock."),
  r("sea-breeze", "Sea Breeze", "cocktail", ["vodka", "cranberry", "grapefruit"], [], 2, "easy", "Third cranberry unlock."),
  r("mezcal-negroni", "Mezcal Negroni", "cocktail", ["mezcal", "campari", "sweet vermouth"], ["orange"], 3, "easy", "Mezcal is the agave miss."),
  r("oaxaca-old-fashioned", "Oaxaca Old Fashioned", "cocktail", ["mezcal", "honey", "angostura"], ["orange"], 4, "easy", "Second mezcal unlock."),
  r("mezcal-margarita", "Mezcal margarita", "cocktail", ["mezcal", "cointreau", "lime"], [], 5, "easy", "Third mezcal unlock."),
  r("mezcal-paloma", "Mezcal Paloma", "cocktail", ["mezcal", "grapefruit", "soda", "lime"], [], 3, "easy", "Fourth mezcal unlock."),
  r("mojito", "Mojito", "cocktail", ["rum", "mint", "lime", "simple syrup"], ["soda"], 6, "medium", "Rum + mint path."),
  r("mai-tai", "Mai Tai", "cocktail", ["rum", "cointreau", "lime", "orgeat"], [], 6, "medium", "Rum and orgeat."),
  r("army-navy", "Army & Navy", "cocktail", ["gin", "orgeat", "lemon"], [], 4, "easy", "Orgeat Smart Buy."),
  r("bourbon-orgeat", "Bourbon orgeat sour", "cocktail", ["bourbon", "orgeat", "lemon"], ["angostura"], 5, "easy", "Second orgeat unlock."),
  r("vesper", "Vesper", "cocktail", ["gin", "vodka", "lillet"], [], 4, "medium", "Lillet is the miss."),
  r("lillet-tonic", "Lillet and tonic", "cocktail", ["lillet", "tonic"], ["orange"], 2, "easy", "Second Lillet unlock."),
  r("scotch-old-fashioned", "Scotch Old Fashioned", "cocktail", ["scotch", "sugar", "angostura"], ["orange"], 4, "easy", "Scotch Smart Buy."),
  r("scotch-sour", "Scotch sour", "cocktail", ["scotch", "lemon", "simple syrup"], [], 4, "easy", "Second scotch unlock."),
  r("irish-coffee", "Irish coffee", "cocktail", ["irish whiskey", "coffee", "sugar", "cream"], [], 6, "easy", "Irish unlock."),
  r("irish-old-fashioned", "Irish Old Fashioned", "cocktail", ["irish whiskey", "sugar", "angostura"], ["orange"], 4, "easy", "Second irish unlock."),
  r("amaretto-sour", "Amaretto sour", "cocktail", ["amaretto", "lemon", "simple syrup"], [], 4, "easy", "Amaretto Smart Buy."),
  r("godfather", "Godfather", "cocktail", ["scotch", "amaretto"], [], 2, "easy", "Scotch + amaretto."),
  r("rusty-nail", "Rusty Nail", "cocktail", ["scotch", "drambuie"], [], 2, "easy", "Drambuie unlock."),
  r("white-negroni", "White Negroni", "cocktail", ["gin", "suze", "lillet"], [], 3, "medium", "Suze + Lillet."),
  r("grasshopper", "Grasshopper", "cocktail", ["creme de menthe", "creme de cacao", "cream"], [], 3, "easy", "Mint + cacao."),
  r("stinger", "Stinger", "cocktail", ["cognac", "creme de menthe"], [], 3, "easy", "Cognac + mint."),
  r("brandy-flip", "Brandy flip", "cocktail", ["cognac", "eggs", "sugar"], [], 5, "medium", "Egg flip."),
  r("rum-punch", "Simple rum punch", "cocktail", ["rum", "orange", "lemon", "sugar", "angostura"], [], 5, "easy", "Rum density."),
  r("mezcal-mule", "Mezcal mule", "cocktail", ["mezcal", "ginger beer", "lime"], [], 3, "easy", "Mezcal unlock."),
  r("chartreuse-tonic", "Chartreuse and tonic", "cocktail", ["chartreuse", "tonic"], ["lime"], 2, "easy", "Chartreuse highball."),
  r("orgeat-gin-fizz", "Gin orgeat fizz", "cocktail", ["gin", "orgeat", "lemon", "soda"], [], 5, "easy", "Orgeat unlock."),
  r("honey-gin", "Honey gin sour", "cocktail", ["gin", "honey", "lemon"], [], 4, "easy", "Sweetener family."),
  r("ginger-bourbon", "Bourbon ginger", "cocktail", ["bourbon", "ginger beer", "lime"], [], 2, "easy", "Mule bones on whiskey."),
  r("campari-orange", "Campari and orange", "cocktail", ["campari", "orange"], [], 1, "easy", "Simplest bitter highball."),
  r("amaro-coffee", "Amaro coffee", "cocktail", ["amaro", "coffee"], [], 2, "easy", "After-dinner on Averna."),
  r("mezcal-old-fashioned", "Mezcal Old Fashioned", "cocktail", ["mezcal", "sugar", "angostura"], ["orange"], 4, "easy", "Seventh mezcal unlock."),
  r("oaxaca-coffee", "Oaxaca coffee", "cocktail", ["mezcal", "coffee", "honey"], [], 4, "easy", "Eighth mezcal unlock."),
  r("gin-fizz", "Gin fizz", "cocktail", ["gin", "lemon", "simple syrup", "soda"], [], 5, "easy", "Classic fizz."),
  r("ramos-gin-fizz", "Ramos gin fizz", "cocktail", ["gin", "lemon", "lime", "simple syrup", "cream", "eggs", "soda"], [], 12, "involved", "Long shake."),
  r("whiskey-smash-mint", "Whiskey smash", "cocktail", ["bourbon", "mint", "lemon", "simple syrup"], [], 6, "medium", "Mint smash."),
  r("corpse-reviver", "Corpse Reviver No. 2", "cocktail", ["gin", "cointreau", "lillet", "lemon"], [], 4, "medium", "Lillet + Cointreau."),
  r("aviation", "Aviation", "cocktail", ["gin", "maraschino", "lemon"], [], 4, "medium", "Maraschino path."),
  r("sazerac-style", "Sazerac style", "cocktail", ["rye", "sugar", "angostura"], ["lemon"], 5, "medium", "Rye and bitters."),
  r("vieux-carre", "Vieux Carré", "cocktail", ["rye", "cognac", "sweet vermouth", "angostura"], [], 4, "medium", "Cognac + rye."),
  r("blood-and-sand", "Blood and Sand", "cocktail", ["scotch", "sweet vermouth", "cointreau", "cherry"], [], 4, "medium", "Scotch + cherry."),
  r("rob-roy", "Rob Roy", "cocktail", ["scotch", "sweet vermouth", "angostura"], [], 3, "easy", "Scotch Manhattan."),
  r("godmother", "Godmother", "cocktail", ["vodka", "amaretto"], [], 2, "easy", "Vodka + amaretto."),
  r("toasted-almond", "Toasted almond", "cocktail", ["amaretto", "coffee liqueur", "cream"], [], 3, "easy", "Amaretto + coffee."),
  r("b-52", "B-52", "cocktail", ["coffee liqueur", "amaretto", "cream"], [], 3, "easy", "Layered shot path."),
  r("irish-maid", "Irish maid", "cocktail", ["irish whiskey", "cucumber", "lemon", "simple syrup"], [], 5, "medium", "Cucumber irish."),
  r("penicillin", "Penicillin", "cocktail", ["scotch", "lemon", "honey", "ginger"], [], 5, "medium", "Scotch honey ginger."),
  r("naked-and-famous", "Naked and Famous", "cocktail", ["mezcal", "chartreuse", "aperol", "lime"], [], 4, "medium", "Mezcal + Chartreuse."),
  r("final-word", "Final Word", "cocktail", ["bourbon", "chartreuse", "maraschino", "lemon"], [], 4, "medium", "Bourbon Last Word."),
  r("chartreuse-swizzle", "Chartreuse swizzle", "cocktail", ["chartreuse", "pineapple", "lime", "simple syrup"], [], 5, "medium", "Chartreuse tropical."),
  r("lillet-spritz", "Lillet spritz", "cocktail", ["lillet", "prosecco", "soda"], ["orange"], 2, "easy", "Lillet + sparkling."),
  r("aperol-mezcal", "Aperol mezcal sour", "cocktail", ["mezcal", "aperol", "lemon"], [], 4, "easy", "Mezcal bitter sour."),
  r("rum-negroni", "Rum Negroni", "cocktail", ["rum", "campari", "sweet vermouth"], ["orange"], 3, "easy", "Rum on Negroni bones."),
  r("tequila-negroni", "Tequila Negroni", "cocktail", ["tequila", "campari", "sweet vermouth"], ["orange"], 3, "easy", "Agave Negroni."),
  r("cynar-spritz", "Amaro spritz", "cocktail", ["amaro", "prosecco", "soda"], ["orange"], 2, "easy", "Amaro + sparkling."),
  r("gin-amaro", "Gin and amaro", "cocktail", ["gin", "amaro", "lemon"], [], 3, "easy", "Gin bitter."),
  r("vodka-cranberry", "Vodka cranberry", "cocktail", ["vodka", "cranberry"], ["lime"], 2, "easy", "Fourth cranberry."),
  r("bay-breeze", "Bay Breeze", "cocktail", ["vodka", "cranberry", "pineapple"], [], 2, "easy", "Fifth cranberry."),
  r("malibu-style", "Coconut rum highball", "cocktail", ["rum", "coconut milk", "pineapple", "soda"], [], 3, "easy", "Tropical highball."),
  r("espresso-bourbon", "Bourbon espresso", "cocktail", ["bourbon", "coffee", "simple syrup"], [], 4, "easy", "Coffee whiskey."),
  r("maple-sour", "Maple sour", "cocktail", ["bourbon", "maple", "lemon"], [], 4, "easy", "Maple sour."),
  r("honey-mezcal", "Honey mezcal sour", "cocktail", ["mezcal", "honey", "lime"], [], 4, "easy", "Mezcal honey."),
  r("ginger-gin", "Gin ginger", "cocktail", ["gin", "ginger beer", "lime"], [], 2, "easy", "Gin mule."),
  r("tonic-amaro", "Amaro tonic", "cocktail", ["amaro", "tonic"], ["orange"], 2, "easy", "Bitter tonic."),
  r("soda-cognac", "Cognac soda", "cocktail", ["cognac", "soda"], ["lemon"], 2, "easy", "Fifth cognac."),
  r("chartreuse-on-rocks", "Chartreuse rocks", "cocktail", ["chartreuse"], [], 1, "easy", "Fourth Chartreuse."),
  r("lillet-on-rocks", "Lillet rocks", "cocktail", ["lillet"], ["orange"], 1, "easy", "Third Lillet."),
  r("orgeat-lemonade", "Orgeat lemonade", "cocktail", ["orgeat", "lemon", "soda"], [], 3, "easy", "Third orgeat."),
  r("cranberry-gin", "Gin cranberry", "cocktail", ["gin", "cranberry", "lime"], [], 2, "easy", "Gin cranberry."),
  r("mezcal-tonic", "Mezcal tonic", "cocktail", ["mezcal", "tonic"], ["lime"], 2, "easy", "Mezcal highball."),
];
