import type { Recipe, RecipeKind, Skill } from "./types";

function r(
  id: string,
  name: string,
  kind: RecipeKind,
  required: string[],
  optional: string[],
  minutes: number,
  skill: Skill,
  notes: string,
): Recipe {
  return { id, name, kind, required, optional, minutes, skill, notes };
}

/** Food recipes batch B (SEED_VERSION 6). */
export const FOOD_RECIPES_B: Recipe[] = [
  r("egg-salad-sandwich", "Egg salad sandwich", "food", ["eggs", "mayo", "bread"], ["dijon", "scallion"], 15, "easy", "Boiled eggs."),
  r("spanish-tortilla", "Spanish tortilla", "food", ["eggs", "potato", "onion", "olive oil"], [], 35, "medium", "One pan."),
  r("shallot-vinaigrette", "Shallot vinaigrette greens", "food", ["lettuce", "shallot", "olive oil", "red wine vinegar"], ["dijon"], 10, "easy", "Simple salad."),
  r("tomato-paste-spaghetti", "Tomato paste spaghetti", "food", ["pasta", "tomato paste", "garlic", "olive oil", "butter"], ["parmesan"], 18, "easy", "Emergency pasta."),
  r("creamed-mushrooms", "Creamed mushrooms", "food", ["mushrooms", "cream", "butter", "garlic"], ["parsley"], 20, "easy", "On toast or rice."),
  r("apple-yogurt", "Apple yogurt", "food", ["apple", "yogurt", "honey"], ["cinnamon"], 5, "easy", "Breakfast."),
  r("peanut-chicken", "Peanut chicken", "food", ["chicken", "peanut butter", "soy sauce", "lime"], ["garlic", "ginger"], 25, "easy", "Nut family."),
  r("rice-pudding", "Rice pudding", "food", ["rice", "milk", "sugar", "vanilla"], ["cinnamon"], 40, "easy", "Uses leftover rice."),
  r("hummus", "Hummus", "food", ["chickpeas", "tahini", "lemon", "garlic", "olive oil"], [], 15, "easy", "Tahini path."),
  r("guacamole", "Guacamole", "food", ["avocado", "lime", "onion", "cilantro"], ["tomato", "jalapeno"], 10, "easy", "Near-expiry avocado."),
  r("avocado-toast", "Avocado toast", "food", ["avocado", "bread", "lemon"], ["chili flakes", "eggs"], 8, "easy", "Near-expiry avocado."),
  r("caprese", "Caprese", "food", ["tomato", "mozzarella", "basil", "olive oil"], [], 8, "easy", "Cheese family."),
  r("greek-salad", "Greek salad", "food", ["cucumber", "tomato", "feta", "olive oil", "onion"], ["olives", "oregano"], 12, "easy", "Feta path."),
  r("risotto", "Parmesan risotto", "food", ["rice", "white wine", "parmesan", "butter", "onion", "stock"], [], 35, "medium", "White wine path."),
  r("carrot-tahini", "Roast carrots with tahini", "food", ["carrot", "tahini", "lemon", "olive oil"], ["garlic"], 30, "easy", "Tahini unlock."),
  r("feta-eggs", "Baked feta eggs", "food", ["feta", "eggs", "tomato", "olive oil"], ["garlic"], 25, "easy", "Feta unlock."),
  r("mozzarella-garlic-bread", "Cheesy garlic bread", "food", ["bread", "mozzarella", "garlic", "butter"], ["parsley"], 12, "easy", "Cheese family."),
  r("chicken-piccata", "Chicken piccata", "food", ["chicken", "lemon", "butter", "capers", "white wine"], ["parsley"], 25, "medium", "White wine path."),
  r("herb-omelette", "Herb omelette with feta", "food", ["eggs", "feta", "parsley", "butter"], ["scallion"], 12, "easy", "Feta unlock."),
  r("lentil-feta", "Lentil feta salad", "food", ["lentils", "feta", "lemon", "olive oil", "onion"], ["parsley"], 25, "easy", "Feta unlock."),
  r("broccoli-feta", "Broccoli feta", "food", ["broccoli", "feta", "olive oil", "lemon", "garlic"], [], 25, "easy", "Feta unlock."),
  r("tahini-cucumber", "Tahini cucumber", "food", ["cucumber", "tahini", "lemon", "garlic"], [], 10, "easy", "Tahini unlock."),
  r("kale-tahini", "Kale with tahini", "food", ["kale", "tahini", "lemon", "garlic"], ["olive oil"], 12, "easy", "Tahini unlock."),
  r("avocado-chicken", "Avocado chicken bowl", "food", ["avocado", "chicken", "rice", "lime"], ["cilantro"], 15, "easy", "Near-expiry avocado."),
  r("mozzarella-pasta", "Tomato mozzarella pasta", "food", ["pasta", "tomato", "mozzarella", "basil", "olive oil"], ["garlic"], 20, "easy", "Cheese family."),
  r("white-wine-shrimp", "White wine shrimp", "food", ["shrimp", "white wine", "garlic", "butter", "parsley"], ["lemon"], 18, "easy", "White wine path."),
  r("mushroom-wine-chicken", "Mushroom wine chicken", "food", ["chicken", "mushrooms", "white wine", "butter", "garlic"], ["parsley"], 30, "medium", "White wine path."),
  r("miso-soup", "Miso soup", "food", ["miso", "stock", "scallion"], [], 12, "easy", "Fridge miso plus a carton of stock."),
  r("anchovy-pasta", "Anchovy garlic pasta", "food", ["pasta", "anchovies", "garlic", "olive oil"], ["parmesan", "chili flakes"], 18, "easy", "The can does the salt work."),
  r("caprese-toast", "Caprese toast", "food", ["bread", "tomato", "mozzarella", "basil"], ["olive oil"], 8, "easy", "Mozzarella is on the cheese family."),
  r("feta-watermelon", "Feta cucumber salad", "food", ["feta", "cucumber", "lemon", "olive oil"], ["mint"], 10, "easy", "Feta unlock. Crisp and salty."),
  r("baked-feta", "Baked feta with tomato", "food", ["feta", "tomato", "olive oil", "garlic"], [], 25, "easy", "One pan."),
  r("tahini-toast", "Tahini honey toast", "food", ["bread", "tahini", "honey"], ["butter"], 5, "easy", "Breakfast path."),
  r("white-wine-mussels", "White wine shallot pan", "food", ["white wine", "shallot", "butter", "garlic"], ["parsley"], 15, "medium", "White wine already in the demo fridge."),
  r("avocado-eggs", "Avocado eggs", "food", ["avocado", "eggs", "bread"], ["chili flakes"], 10, "easy", "Near-expiry avocado."),
  r("mozzarella-tomato-pasta", "Fresh tomato mozzarella pasta", "food", ["pasta", "tomato", "mozzarella", "basil", "olive oil"], ["garlic"], 20, "easy", "Cheese family."),
  r("bean-chili", "Black bean chili", "food", ["black beans", "tomato", "onion", "cumin", "chili flakes"], ["cheddar"], 35, "easy", "Pantry heat."),
  r("ginger-scallion-noodles", "Ginger scallion noodles", "food", ["pasta", "ginger", "scallion", "soy sauce", "sesame oil"], [], 15, "easy", "Classic oil-pull."),
  r("tuna-rice-bowl", "Tuna rice bowl", "food", ["tuna", "rice", "cucumber", "soy sauce"], ["sesame oil", "scallion"], 12, "easy", "Can + leftover rice."),
  r("spinach-feta-eggs", "Spinach feta scramble", "food", ["eggs", "spinach", "feta"], ["butter"], 12, "easy", "Greens before they go."),
  r("coconut-curry-chickpeas", "Coconut chickpea curry", "food", ["chickpeas", "coconut milk", "onion", "garlic", "turmeric", "cumin"], ["ginger"], 30, "easy", "Coconut family in the pantry."),
  r("garlic-shrimp-rice", "Garlic shrimp over rice", "food", ["shrimp", "garlic", "butter", "rice", "lemon"], ["parsley"], 20, "easy", "Frozen shrimp, hot butter."),
  r("soy-broccoli", "Soy ginger broccoli", "food", ["broccoli", "soy sauce", "ginger", "garlic"], ["sesame oil"], 15, "easy", "Uses the broccoli before it yellows."),
  r("berry-smoothie", "Berry yogurt smoothie", "food", ["berries", "yogurt", "honey", "milk"], [], 5, "easy", "Frozen berries before they frost-burn."),
  r("peanut-satay-chicken", "Peanut satay chicken", "food", ["chicken", "peanut butter", "soy sauce", "lime", "garlic"], ["ginger"], 25, "easy", "Nut family already open."),
  r("caper-chicken", "Chicken with capers and lemon", "food", ["chicken", "capers", "lemon", "butter"], ["parsley"], 25, "easy", "Piccata cousin without the wine."),
  r("miso-glazed-eggplant", "Miso glazed vegetables", "food", ["miso", "honey", "soy sauce", "broccoli"], ["sesame oil"], 25, "easy", "Miso glaze."),
  r("feta-orzo", "Feta orzo", "food", ["pasta", "feta", "lemon", "olive oil", "garlic"], ["parsley"], 20, "easy", "Feta pasta."),
  r("tahini-noodles", "Tahini noodles", "food", ["pasta", "tahini", "soy sauce", "garlic", "lime"], ["scallion"], 15, "easy", "Tahini noodles."),
  r("avocado-tuna", "Avocado tuna salad", "food", ["avocado", "tuna", "lime", "onion"], ["cilantro"], 10, "easy", "No mayo."),
  r("prosecco-risotto", "Prosecco risotto", "food", ["rice", "prosecco", "parmesan", "butter", "onion", "stock"], [], 35, "medium", "Sparkling path."),
  r("mint-yogurt-cucumber", "Mint yogurt cucumber", "food", ["cucumber", "yogurt", "mint", "lemon", "garlic"], [], 10, "easy", "Mint path."),
  r("basil-mozzarella-eggs", "Basil mozzarella scramble", "food", ["eggs", "mozzarella", "basil", "butter"], [], 10, "easy", "Cheese + herb."),
  r("white-wine-mushrooms", "White wine mushrooms", "food", ["mushrooms", "white wine", "butter", "garlic", "parsley"], [], 15, "easy", "Wine path."),
  r("feta-tomato-toast", "Feta tomato toast", "food", ["bread", "feta", "tomato", "olive oil"], ["oregano"], 8, "easy", "Feta toast."),
  r("tahini-eggs", "Tahini eggs", "food", ["eggs", "tahini", "lemon", "garlic"], ["chili flakes"], 12, "easy", "Tahini breakfast."),
  r("avocado-rice-bowl", "Avocado rice bowl", "food", ["avocado", "rice", "soy sauce", "scallion"], ["sesame oil", "cucumber"], 12, "easy", "Near-expiry avocado."),
  r("mozzarella-spinach", "Mozzarella spinach melt", "food", ["spinach", "mozzarella", "garlic", "olive oil"], ["bread"], 12, "easy", "Cheese + greens."),
  r("prosecco-fruit", "Prosecco berries", "food", ["prosecco", "berries"], ["honey"], 2, "easy", "Sparkling dessert."),
  r("mint-peas", "Minted peas", "food", ["peas", "mint", "butter"], ["lemon"], 10, "easy", "Frozen peas + mint."),
  r("oregano-chicken", "Oregano lemon chicken", "food", ["chicken", "oregano", "lemon", "olive oil", "garlic"], [], 30, "easy", "Herb path."),
  r("cinnamon-oats", "Cinnamon oats", "food", ["oats", "milk", "cinnamon", "honey"], [], 10, "easy", "Warm breakfast."),
  r("cinnamon-apple", "Cinnamon apples", "food", ["apple", "cinnamon", "butter", "honey"], [], 12, "easy", "Dessert path."),
  r("fish-sauce-noodles", "Fish sauce noodles", "food", ["pasta", "fish sauce", "lime", "garlic", "sugar"], ["chili flakes", "scallion"], 15, "easy", "Southeast Asian pantry."),
  r("anchovy-toast", "Anchovy butter toast", "food", ["bread", "anchovies", "butter", "garlic"], ["parsley"], 8, "easy", "Umami toast."),
  r("capers-lemon-fish", "Caper lemon tuna", "food", ["tuna", "capers", "lemon", "olive oil"], ["parsley"], 10, "easy", "No cook."),
  r("shallot-pasta", "Shallot butter pasta", "food", ["pasta", "shallot", "butter", "parmesan"], ["parsley"], 18, "easy", "Allium path."),
  r("jalapeno-eggs", "Jalapeño eggs", "food", ["eggs", "jalapeno", "cheddar", "butter"], [], 12, "easy", "Spicy scramble."),
];
