import type { Recipe, RecipeKind, Skill } from "./types";

function r(
  id: string,
  name: string,
  kind: RecipeKind,
  required: string[],
  optional: string[],
  minutes: number,
  skill: Skill,
  notes: string,
): Recipe {
  return { id, name, kind, required, optional, minutes, skill, notes };
}

/** Food recipes batch A (SEED_VERSION 6). */
export const FOOD_RECIPES_A: Recipe[] = [
  r("lemon-butter-pasta", "Lemon butter pasta", "food", ["pasta", "butter", "lemon", "parmesan"], ["garlic"], 20, "easy", "Weeknight default. Uses the lemon before it fades."),
  r("aglio-olio", "Aglio e olio", "food", ["pasta", "garlic", "olive oil"], ["parmesan", "chili flakes"], 18, "easy", "Pantry-true. Hierarchy does not invent missing oil."),
  r("tomato-spaghetti", "Tomato garlic spaghetti", "food", ["pasta", "tomato", "garlic", "olive oil"], ["parmesan", "basil"], 30, "easy", "High co-occurrence trio: tomato, garlic, oil."),
  r("chicken-bowl", "Roast chicken grain bowl", "food", ["chicken", "rice", "kale", "lemon"], ["olive oil"], 25, "easy", "Prioritizes leftover chicken and near-expiry greens."),
  r("chicken-dijon", "Chicken Dijon skillet", "food", ["chicken", "dijon", "onion"], ["milk", "butter"], 28, "medium", "Uses roast chicken without asking for a new protein."),
  r("kale-parmesan", "Lemon kale with parmesan", "food", ["kale", "lemon", "parmesan"], ["olive oil", "garlic"], 12, "easy", "The expiry-first salad. Fat and acid fix the brassica."),
  r("omelette", "French omelette", "food", ["eggs", "butter"], ["parmesan"], 8, "medium", "Two-ingredient truth. Skill is the only hard part."),
  r("potato-hash", "Potato hash with eggs", "food", ["potato", "eggs", "onion", "butter"], ["cheddar"], 25, "easy", "Uses the potatoes before they sprout."),
  r("honey-carrots", "Honey roasted carrots", "food", ["carrot", "honey", "butter"], ["dijon"], 30, "easy", "Sweetener family covers if maple is the only option."),
  r("beans-rice", "Black beans and rice", "food", ["black beans", "rice", "onion", "cumin"], ["lime", "cilantro"], 25, "easy", "Pantry core. Hierarchy covers bean family."),
  r("pesto-pasta", "Herb pesto pasta", "food", ["pasta", "basil", "garlic", "parmesan", "olive oil"], ["lemon"], 15, "easy", "Uses the basil before it blackens."),
  r("fried-rice", "Vegetable fried rice", "food", ["rice", "eggs", "soy sauce", "scallion", "garlic"], ["ginger", "peas"], 20, "easy", "Leftover rice is the point."),
  r("tuna-chickpea", "Tuna chickpea salad", "food", ["tuna", "chickpeas", "lemon", "olive oil"], ["onion", "parsley"], 10, "easy", "Two cans, no heat."),
  r("grilled-cheese", "Grilled cheese", "food", ["bread", "cheddar", "butter"], [], 10, "easy", "Freezer bread thaws in the pan."),
  r("yogurt-honey", "Honey yogurt", "food", ["yogurt", "honey"], [], 3, "easy", "Breakfast that costs nothing extra."),
  r("overnight-oats", "Overnight oats", "food", ["oats", "milk", "honey"], ["yogurt"], 8, "easy", "Ranks high while the milk is still honest."),
  r("spinach-eggs", "Wilted spinach eggs", "food", ["eggs", "spinach", "butter"], ["parmesan"], 12, "easy", "Uses the spinach before it weeps."),
  r("chicken-noodle", "Chicken noodle soup", "food", ["chicken", "pasta", "carrot", "onion", "stock"], ["celery", "parsley"], 35, "easy", "Leftover chicken plus a box of stock."),
  r("carbonara", "Carbonara", "food", ["pasta", "eggs", "parmesan", "bacon"], ["black pepper"], 20, "medium", "No cream. Eggs and fat are the sauce."),
  r("cacio-e-pepe", "Cacio e pepe", "food", ["pasta", "parmesan", "black pepper"], ["butter"], 15, "medium", "Three names. The water is the fourth."),
  r("garlic-bread", "Garlic bread", "food", ["bread", "garlic", "butter"], ["parsley"], 12, "easy", "The freezer loaf earns its keep."),
  r("shrimp-scampi", "Shrimp scampi", "food", ["shrimp", "garlic", "butter", "lemon", "pasta"], ["parsley"], 20, "easy", "Frozen shrimp, hot pan, lemon at the end."),
  r("black-bean-tacos", "Black bean tacos", "food", ["black beans", "tortillas", "onion", "lime"], ["cheddar"], 18, "easy", "Weeknight taco math without a new protein."),
  r("migas", "Migas", "food", ["eggs", "tortillas", "cheddar", "onion"], ["tomato"], 15, "easy", "Eggs stretch leftover tortillas."),
  r("lentil-soup", "Lentil soup", "food", ["lentils", "carrot", "onion", "garlic", "stock"], ["olive oil"], 40, "easy", "Dry lentils, no soak, one pot."),
  r("sesame-noodles", "Sesame garlic noodles", "food", ["pasta", "soy sauce", "sesame oil", "garlic", "ginger"], ["chili flakes"], 18, "easy", "Cold or hot. The sauce is pantry-true."),
  r("tomato-chickpea-stew", "Tomato chickpea stew", "food", ["chickpeas", "tomato", "onion", "garlic", "olive oil"], ["paprika"], 30, "easy", "Canned tomato covers if the fresh ones are gone."),
  r("bacon-and-eggs", "Bacon and eggs", "food", ["bacon", "eggs"], ["butter"], 15, "easy", "The shortest honest breakfast."),
  r("kale-chickpea", "Garlicky kale and chickpeas", "food", ["kale", "chickpeas", "garlic", "olive oil", "lemon"], [], 18, "easy", "Expiry greens plus a can."),
  r("chicken-lemon-pasta", "Chicken lemon pasta", "food", ["chicken", "pasta", "lemon", "butter", "parmesan"], ["garlic"], 25, "easy", "Leftover chicken, bright finish."),
  r("mustard-chicken-potato", "Mustard chicken with potatoes", "food", ["chicken", "dijon", "potato", "onion"], ["butter"], 35, "easy", "Sheet-pan path."),
  r("puttanesca", "Puttanesca", "food", ["pasta", "tomato", "anchovies", "olives", "capers", "garlic", "olive oil"], ["chili flakes"], 25, "easy", "Pantry salt and acid."),
  r("ginger-carrot-soup", "Ginger carrot soup", "food", ["carrot", "ginger", "onion", "stock"], ["coconut milk"], 35, "easy", "Uses the carrots."),
  r("cucumber-yogurt", "Cucumber yogurt", "food", ["cucumber", "yogurt", "lemon", "garlic"], ["mint"], 10, "easy", "Cool side."),
  r("shakshuka", "Shakshuka", "food", ["eggs", "tomato", "onion", "garlic", "cumin"], ["chili flakes", "feta"], 30, "easy", "Eggs in tomato."),
  r("french-toast", "French toast", "food", ["bread", "eggs", "milk", "butter"], ["honey"], 15, "easy", "Stale bread earns its keep."),
  r("tuna-pasta", "Tuna pasta", "food", ["pasta", "tuna", "olive oil", "lemon"], ["parsley", "garlic"], 18, "easy", "Two cans."),
  r("tomato-soup", "Tomato soup", "food", ["tomato", "onion", "garlic", "stock", "butter"], ["cream"], 30, "easy", "Canned tomato path."),
  r("chicken-fried-rice", "Chicken fried rice", "food", ["chicken", "rice", "eggs", "soy sauce", "scallion"], ["ginger", "peas"], 20, "easy", "Leftover chicken and rice."),
  r("parsley-garlic-shrimp", "Parsley garlic shrimp", "food", ["shrimp", "garlic", "butter", "parsley", "lemon"], [], 15, "easy", "Hot pan, frozen shrimp."),
  r("celery-stock-soup", "Celery stock soup", "food", ["celery", "onion", "stock", "butter"], ["potato"], 30, "easy", "Uses the celery."),
  r("chili-oil-noodles", "Chili oil noodles", "food", ["pasta", "chili flakes", "soy sauce", "garlic", "sesame oil"], ["scallion"], 15, "easy", "Pantry heat."),
  r("miso-butter-chicken", "Miso butter chicken", "food", ["chicken", "miso", "butter", "garlic"], ["scallion"], 25, "easy", "Fridge miso."),
  r("sumac-chicken", "Sumac chicken", "food", ["chicken", "sumac", "lemon", "olive oil", "garlic"], [], 30, "easy", "Bright spice."),
  r("ginger-soy-greens", "Ginger soy greens", "food", ["kale", "ginger", "soy sauce", "garlic", "sesame oil"], [], 12, "easy", "Expiry greens."),
  r("chickpea-cumin", "Cumin chickpeas", "food", ["chickpeas", "cumin", "onion", "garlic", "olive oil"], ["lemon"], 20, "easy", "Pulse and spice."),
  r("coconut-turmeric-rice", "Coconut turmeric rice", "food", ["rice", "coconut milk", "turmeric", "onion"], ["cumin"], 25, "easy", "Coconut family."),
  r("mac-and-cheese", "Mac and cheese", "food", ["pasta", "cheddar", "milk", "butter"], [], 25, "easy", "Cheese family."),
  r("tuna-melt", "Tuna melt", "food", ["tuna", "bread", "cheddar", "butter"], ["mayo"], 12, "easy", "Toaster path."),
  r("kale-caesar", "Kale Caesar", "food", ["kale", "parmesan", "lemon", "olive oil", "anchovies"], ["garlic"], 15, "easy", "Anchovy dressing."),
  r("pea-pasta", "Pea pasta", "food", ["pasta", "peas", "butter", "parmesan"], ["lemon"], 18, "easy", "Frozen peas."),
  r("honey-mustard-chicken", "Honey mustard chicken", "food", ["chicken", "honey", "dijon"], ["garlic"], 25, "easy", "Sweet-sharp glaze."),
  r("soy-ginger-chicken", "Soy ginger chicken", "food", ["chicken", "soy sauce", "ginger", "garlic"], ["sesame oil"], 25, "easy", "Weeknight marinade."),
  r("mushroom-pasta", "Mushroom pasta", "food", ["pasta", "mushrooms", "butter", "garlic", "parmesan"], ["parsley"], 25, "easy", "Earthy."),
  r("pico-de-gallo", "Pico de gallo", "food", ["tomato", "onion", "lime", "cilantro"], ["jalapeno"], 10, "easy", "No cook."),
  r("cilantro-lime-rice", "Cilantro lime rice", "food", ["rice", "lime", "cilantro"], ["butter"], 20, "easy", "Bright side."),
  r("chicken-tacos", "Chicken tacos", "food", ["chicken", "tortillas", "onion", "lime"], ["cilantro", "cheddar"], 20, "easy", "Leftover chicken."),
  r("shrimp-tacos", "Shrimp tacos", "food", ["shrimp", "tortillas", "lime", "cabbage"], ["cilantro"], 18, "easy", "Frozen shrimp."),
  r("roasted-broccoli", "Roasted broccoli", "food", ["broccoli", "olive oil", "garlic", "lemon"], ["parmesan"], 25, "easy", "Uses the broccoli."),
  r("peanut-noodles", "Peanut noodles", "food", ["pasta", "peanut butter", "soy sauce", "lime", "garlic"], ["ginger", "chili flakes"], 18, "easy", "Nut family."),
  r("nuoc-cham", "Nuoc cham cucumber", "food", ["cucumber", "fish sauce", "lime", "sugar", "garlic"], ["chili flakes"], 10, "easy", "Fish sauce path."),
  r("coconut-rice", "Coconut rice", "food", ["rice", "coconut milk"], ["salt"], 20, "easy", "Simple coconut."),
  r("coconut-lime-shrimp", "Coconut lime shrimp", "food", ["shrimp", "coconut milk", "lime", "garlic"], ["ginger"], 20, "easy", "Tropical skillet."),
  r("maple-dijon-chicken", "Maple Dijon chicken", "food", ["chicken", "maple", "dijon"], [], 25, "easy", "Sweetener family."),
  r("smashed-cucumber", "Smashed cucumber", "food", ["cucumber", "soy sauce", "rice vinegar", "garlic", "sesame oil"], ["chili flakes"], 10, "easy", "Cold and crunchy."),
  r("pantry-pomodoro", "Pantry pomodoro", "food", ["pasta", "tomato paste", "garlic", "olive oil"], ["basil", "parmesan"], 20, "easy", "Paste path."),
  r("blt", "BLT", "food", ["bacon", "bread", "lettuce", "tomato", "mayo"], [], 15, "easy", "Classic."),
  r("ginger-honey-lemon", "Ginger honey lemon", "food", ["ginger", "honey", "lemon"], ["hot water"], 5, "easy", "Soothing mug."),
  r("berry-yogurt", "Berry yogurt bowl", "food", ["berries", "yogurt", "honey"], [], 5, "easy", "Frozen berries."),
  r("scallion-eggs", "Scallion eggs", "food", ["eggs", "scallion", "butter"], ["soy sauce"], 10, "easy", "Fast."),
  r("hot-sauce-eggs", "Hot sauce eggs", "food", ["eggs", "hot sauce", "butter"], ["bread"], 8, "easy", "Spicy breakfast."),
  r("shrimp-fried-rice", "Shrimp fried rice", "food", ["shrimp", "rice", "eggs", "soy sauce", "scallion"], ["ginger", "peas"], 20, "easy", "Frozen shrimp."),
  r("black-bean-soup", "Black bean soup", "food", ["black beans", "onion", "cumin", "stock", "garlic"], ["lime"], 30, "easy", "Can path."),
  r("pepper-rice-skillet", "Pepper rice skillet", "food", ["rice", "bell pepper", "onion", "garlic", "olive oil"], ["cumin"], 25, "easy", "Uses the pepper."),
  r("sunday-pancakes", "Sunday pancakes", "food", ["flour", "eggs", "milk", "butter"], ["honey"], 25, "easy", "Weekend."),
  r("olive-tapenade", "Olive tapenade toast", "food", ["olives", "bread", "garlic", "olive oil"], ["anchovies"], 10, "easy", "Briny toast."),
  r("creamed-spinach", "Creamed spinach", "food", ["spinach", "cream", "butter", "garlic"], ["parmesan"], 15, "easy", "Expiry greens."),
  r("sour-cream-potatoes", "Sour cream potatoes", "food", ["potato", "sour cream", "butter", "scallion"], [], 30, "easy", "Comfort."),
  r("lentil-salad", "Lentil salad", "food", ["lentils", "lemon", "olive oil", "onion"], ["parsley", "feta"], 30, "easy", "Make-ahead."),
  r("tomato-toast", "Tomato toast", "food", ["bread", "tomato", "olive oil", "garlic"], ["basil"], 8, "easy", "Summer path."),
  r("parmesan-potatoes", "Parmesan potatoes", "food", ["potato", "parmesan", "olive oil", "garlic"], [], 35, "easy", "Crispy."),
  r("corn-cilantro-salad", "Corn cilantro salad", "food", ["corn", "cilantro", "lime", "onion"], ["feta"], 10, "easy", "Frozen corn."),
  r("maple-oats", "Maple oats", "food", ["oats", "milk", "maple"], ["butter"], 10, "easy", "Sweetener family."),
  r("worcestershire-chicken", "Worcestershire chicken", "food", ["chicken", "worcestershire", "butter", "garlic"], [], 25, "easy", "Savory glaze."),
];
