import type { Recipe, RecipeKind, Skill } from "./types";

function r(
  id: string,
  name: string,
  kind: RecipeKind,
  required: string[],
  optional: string[],
  minutes: number,
  skill: Skill,
  notes: string,
): Recipe {
  return { id, name, kind, required, optional, minutes, skill, notes };
}

/** Food half of the curated corpus (SEED_VERSION 6). */
export const FOOD_RECIPES: Recipe[] = [
  r("lemon-butter-pasta", "Lemon butter pasta", "food", ["pasta", "butter", "lemon", "parmesan"], ["garlic"], 20, "easy", "Weeknight default. Uses the lemon before it fades."),
  r("aglio-olio", "Aglio e olio", "food", ["pasta", "garlic", "olive oil"], ["parmesan", "chili flakes"], 18, "easy", "Pantry-true. Hierarchy does not invent missing oil."),
  r("tomato-spaghetti", "Tomato garlic spaghetti", "food", ["pasta", "tomato", "garlic", "olive oil"], ["parmesan", "basil"], 30, "easy", "High co-occurrence trio: tomato, garlic, oil."),
  r("chicken-bowl", "Roast chicken grain bowl", "food", ["chicken", "rice", "kale", "lemon"], ["olive oil"], 25, "easy", "Prioritizes leftover chicken and near-expiry greens."),
  r("chicken-dijon", "Chicken Dijon skillet", "food", ["chicken", "dijon", "onion"], ["milk", "butter"], 28, "medium", "Uses roast chicken without asking for a new protein."),
  r("kale-parmesan", "Lemon kale with parmesan", "food", ["kale", "lemon", "parmesan"], ["olive oil", "garlic"], 12, "easy", "The expiry-first salad. Fat and acid fix the brassica."),
  r("omelette", "French omelette", "food", ["eggs", "butter"], ["parmesan"], 8, "medium", "Two-ingredient truth. Skill is the only hard part."),
  r("potato-hash", "Potato hash with eggs", "food", ["potato", "eggs", "onion", "butter"], ["cheddar"], 25, "easy", "Uses the potatoes before they sprout."),
  r("honey-carrots", "Honey roasted carrots", "food", ["carrot", "honey", "butter"], ["dijon"], 30, "easy", "Sweetener family covers if maple is the only option."),
  r("beans-rice", "Black beans and rice", "food", ["black beans", "rice", "onion", "cumin"], ["lime", "cilantro"], 25, "easy", "Pantry core. Hierarchy covers bean family."),
  r("pesto-pasta", "Herb pesto pasta", "food", ["pasta", "basil", "garlic", "parmesan", "olive oil"], ["lemon"], 15, "easy", "Uses the basil before it blackens."),
  r("fried-rice", "Vegetable fried rice", "food", ["rice", "eggs", "soy sauce", "scallion", "garlic"], ["ginger", "peas"], 20, "easy", "Leftover rice is the point."),
  r("tuna-chickpea", "Tuna chickpea salad", "food", ["tuna", "chickpeas", "lemon", "olive oil"], ["onion", "parsley"], 10, "easy", "Two cans, no heat."),
  r("grilled-cheese", "Grilled cheese", "food", ["bread", "cheddar", "butter"], [], 10, "easy", "Freezer bread thaws in the pan."),
  r("yogurt-honey", "Honey yogurt", "food", ["yogurt", "honey"], [], 3, "easy", "Breakfast that costs nothing extra."),
  r("overnight-oats", "Overnight oats", "food", ["oats", "milk", "honey"], ["yogurt"], 8, "easy", "Ranks high while the milk is still honest."),
  r("spinach-eggs", "Wilted spinach eggs", "food", ["eggs", "spinach", "butter"], ["parmesan"], 12, "easy", "Uses the spinach before it weeps."),
  r("chicken-noodle", "Chicken noodle soup", "food", ["chicken", "pasta", "carrot", "onion", "stock"], ["celery", "parsley"], 35, "easy", "Leftover chicken plus a box of stock."),
  r("carbonara", "Carbonara", "food", ["pasta", "eggs", "parmesan", "bacon"], ["black pepper"], 20, "medium", "No cream. Eggs and fat are the sauce."),
  r("cacio-e-pepe", "Cacio e pepe", "food", ["pasta", "parmesan", "black pepper"], ["butter"], 15, "medium", "Three names. The water is the fourth."),
  r("garlic-bread", "Garlic bread", "food", ["bread", "garlic", "butter"], ["parsley"], 12, "easy", "The freezer loaf earns its keep."),
  r("shrimp-scampi", "Shrimp scampi", "food", ["shrimp", "garlic", "butter", "lemon", "pasta"], ["parsley"], 20, "easy", "Frozen shrimp, hot pan, lemon at the end."),
  r("black-bean-tacos", "Black bean tacos", "food", ["black beans", "tortillas", "onion", "lime"], ["cheddar"], 18, "easy", "Weeknight taco math without a new protein."),
  r("migas", "Migas", "food", ["eggs", "tortillas", "cheddar", "onion"], ["tomato"], 15, "easy", "Eggs stretch leftover tortillas."),
  r("lentil-soup", "Lentil soup", "food", ["lentils", "carrot", "onion", "garlic", "stock"], ["olive oil"], 40, "easy", "Dry lentils, no soak, one pot."),
  r("sesame-noodles", "Sesame garlic noodles", "food", ["pasta", "soy sauce", "sesame oil", "garlic", "ginger"], ["chili flakes"], 18, "easy", "Cold or hot. The sauce is pantry-true."),
  r("tomato-chickpea-stew", "Tomato chickpea stew", "food", ["chickpeas", "tomato", "onion", "garlic", "olive oil"], ["paprika"], 30, "easy", "Canned tomato covers if the fresh ones are gone."),
  r("bacon-and-eggs", "Bacon and eggs", "food", ["bacon", "eggs"], ["butter"], 15, "easy", "The shortest honest breakfast."),
  r("kale-chickpea", "Garlicky kale and chickpeas", "food", ["kale", "chickpeas", "garlic", "olive oil", "lemon"], [], 18, "easy", "Expiry greens plus a can."),
  r("miso-soup", "Miso soup", "food", ["miso", "stock", "scallion"], [], 12, "easy", "Fridge miso plus a carton of stock."),
  r("anchovy-pasta", "Anchovy garlic pasta", "food", ["pasta", "anchovies", "garlic", "olive oil"], ["parmesan", "chili flakes"], 18, "easy", "The can does the salt work."),
  r("caprese-toast", "Caprese toast", "food", ["bread", "tomato", "mozzarella", "basil"], ["olive oil"], 8, "easy", "Mozzarella is on the cheese family."),
  r("feta-watermelon", "Feta cucumber salad", "food", ["feta", "cucumber", "lemon", "olive oil"], ["mint"], 10, "easy", "Feta unlock. Crisp and salty."),
  r("baked-feta", "Baked feta with tomato", "food", ["feta", "tomato", "olive oil", "garlic"], [], 25, "easy", "One pan."),
  r("tahini-toast", "Tahini honey toast", "food", ["bread", "tahini", "honey"], ["butter"], 5, "easy", "Breakfast path."),
  r("white-wine-mussels", "White wine shallot pan", "food", ["white wine", "shallot", "butter", "garlic"], ["parsley"], 15, "medium", "White wine already in the demo fridge."),
  r("avocado-eggs", "Avocado eggs", "food", ["avocado", "eggs", "bread"], ["chili flakes"], 10, "easy", "Near-expiry avocado."),
  r("mozzarella-tomato-pasta", "Fresh tomato mozzarella pasta", "food", ["pasta", "tomato", "mozzarella", "basil", "olive oil"], ["garlic"], 20, "easy", "Cheese family."),
  r("bean-chili", "Black bean chili", "food", ["black beans", "tomato", "onion", "cumin", "chili flakes"], ["cheddar"], 35, "easy", "Pantry heat."),
  r("ginger-scallion-noodles", "Ginger scallion noodles", "food", ["pasta", "ginger", "scallion", "soy sauce", "sesame oil"], [], 15, "easy", "Classic oil-pull."),
  r("tuna-rice-bowl", "Tuna rice bowl", "food", ["tuna", "rice", "cucumber", "soy sauce"], ["sesame oil", "scallion"], 12, "easy", "Can + leftover rice."),
  r("spinach-feta-eggs", "Spinach feta scramble", "food", ["eggs", "spinach", "feta"], ["butter"], 12, "easy", "Greens before they go."),
  r("coconut-curry-chickpeas", "Coconut chickpea curry", "food", ["chickpeas", "coconut milk", "onion", "garlic", "turmeric", "cumin"], ["ginger"], 30, "easy", "Coconut family in the pantry."),
  r("garlic-shrimp-rice", "Garlic shrimp over rice", "food", ["shrimp", "garlic", "butter", "rice", "lemon"], ["parsley"], 20, "easy", "Frozen shrimp, hot butter."),
  r("soy-broccoli", "Soy ginger broccoli", "food", ["broccoli", "soy sauce", "ginger", "garlic"], ["sesame oil"], 15, "easy", "Uses the broccoli before it yellows."),
  r("berry-smoothie", "Berry yogurt smoothie", "food", ["berries", "yogurt", "honey", "milk"], [], 5, "easy", "Frozen berries before they frost-burn."),
  r("peanut-satay-chicken", "Peanut satay chicken", "food", ["chicken", "peanut butter", "soy sauce", "lime", "garlic"], ["ginger"], 25, "easy", "Nut family already open."),
  r("caper-chicken", "Chicken with capers and lemon", "food", ["chicken", "capers", "lemon", "butter"], ["parsley"], 25, "easy", "Piccata cousin without the wine."),
];
